### ISSUE TITLE
after installation getting error 

### ISSUE THREAD

**Issue by zeeshanmudassir** [Jetserver/WHMCS-CSF-Manager#11]
[Screenshot](https://i.imgur.com/mQdlqKN.png)

```
Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.

If the problem persists, please [contact us](mailto:sales@hoster.pk).

[« Back to Homepage](https://hoster.pk/clientarea)

For additional assistance, please reference the [WHMCS TroubleShooting Guide »](https://docs.whmcs.com/Troubleshooting_Guide)

BadFunctionCallException: mysql_free_result is not supported in /home/hostersp/domains/hoster.pk/public_html/clientarea/includes/dbcompatfunctions.php:0
Stack trace:
#0 /home/hostersp/domains/hoster.pk/public_html/clientarea/modules/addons/csfmanager/includes/functions.php(28): mysql_free_result(Object(PDOStatement))
#1 /home/hostersp/domains/hoster.pk/public_html/clientarea/modules/addons/csfmanager/includes/functions.php(36): csfmanager->__construct()
#2 /home/hostersp/domains/hoster.pk/public_html/clientarea/modules/addons/csfmanager/csfmanager.php(167): csfmanager::getInstance()
#3 /home/hostersp/domains/hoster.pk/public_html/clientarea/zee/addonmodules.php(0): csfmanager_output(Array)
#4 {main}
```

**Comment by Aveldominguez** [comment]
I have the same error. Any idea?

**Comment by vishalbhan23** [comment]
Simply, change mysql_free_result to mysqli_free_result

**Comment by zeeshanmudassir** [comment]
Where?
And what is difference
You wrote same
