### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by charliehu** [Jetserver/WHMCS-CSF-Manager#2]
Hi,

I downloaded and activated this module, but when i try to open it under Addon modles, i got this PHP error messages:

`Fatal error: Uncaught BadFunctionCallException: mysql_free_result is not supported in /home/whmcs/includes/dbcompatfunctions.php:0 Stack trace: #0 /home/whmcs/modules/addons/csfmanager/includes/functions.php(28): mysql_free_result(Object(PDOStatement)) #1 /home/whmcs/modules/addons/csfmanager/includes/functions.php(36): csfmanager->__construct() #2 /home/whmcs/modules/addons/csfmanager/csfmanager.php(167): csfmanager::getInstance() #3 [internal function]: csfmanager_output(Array) #4 /home/whmcs/fonok/addonmodules.php(0): call_user_func('csfmanager_outp...', Array) #5 {main} Next BadFunctionCallException: mysql_free_result is not supported in /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Terminus.php:0 Stack trace: #0 [internal function]: WHMCS\Terminus::whmcsExceptionHandler(Object(BadFunctionCallException)) #1 {main} thrown in /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Terminus.php on line 0`

PHP version is 7:
`PHP 7.0.17 (cli) (built: Mar 19 2017 14:34:58) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.9, Copyright (c) 2002-2016, by ionCube Ltd.`

**Comment by Jetserver** [comment]
Hello,

This module is not supporting PHP 7 only 5.4 or 5.6.

**Comment by lcwsoft** [comment]
My pull request gets its working with PHP 7 and WHMCS 7 for now (thanks to WHMCS emulating most of the mysql_* functions except mysql_free_result). In the long term, porting the DB logic to the newer Capsule layer WHMCS provides will be best, but no time for that right now from me unfortunately.
