### ISSUE TITLE
Error After Installing

### ISSUE THREAD

**Issue by chad-abizeid** [Jetserver/WHMCS-CSF-Manager#9]
```

Oops!
Something went wrong and we couldn't process your request.

Please go back to the previous page and try again.

If the problem persists, please contact us.

« Back to Homepage

For additional assistance, please reference the WHMCS TroubleShooting Guide »

BadFunctionCallException: mysql_free_result is not supported in /home/xxxxxxx/public_html/billing/includes/dbcompatfunctions.php:0
Stack trace:
#0 /home/xxxxxxx/public_html/billing/modules/addons/csfmanager/includes/functions.php(28): mysql_free_result(false)
#1 /home/xxxxxxx/public_html/billing/modules/addons/csfmanager/includes/functions.php(36): csfmanager->__construct()
#2 /home/xxxxxxx/public_html/billing/modules/addons/csfmanager/csfmanager.php(167): csfmanager::getInstance()
#3 /home/xxxxxxx/public_html/billing/admin-access-only/addonmodules.php(0): csfmanager_output(Array)
#4 {main}

```

**Comment by twhiting9275** [comment]
mysql_xxx is dead... Long live mysql_xxx
With mysql_xxx being dead, that means this program is effectively dead until someone gets off their ass and rewrites it to be forward thinking.
